name: lunofono_player
description: A Flutter widget to play content bundles for Lunofono, the media
  player for kids.
version: 0.0.1
repository: https://github.com/lunofono/lunofono_player

# To be removed when it is published
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  audioplayers: ^0.20.0
  flutter:
    sdk: flutter

  lunofono_bundle:
    git:
      url: https://github.com/lunofono/lunofono_bundle.git
      ref: v0.4.1

  pausable_timer: ^1.0.0+1
  provider: ^6.0.0
  video_player: ^2.1.15
  wakelock: ^0.5.3+3

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  pedantic: ^1.11.1
  test: ^1.17.10
  video_player_platform_interface: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
